import type {Metadata} from "next";
import {Manrope} from "next/font/google";
import "./globals.css";
import {Header} from "@/components/shared/header";
import {Footer} from "@/components/shared/footer";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["cyrillic"],
  weight: ["200", "400", "500", "600", "700", "800"], // ExtraLight, Regular, Medium, SemiBold, Bold, ExtraBold
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="ru">
      <body
          className={`${manrope.variable} antialiased`}
      >
      <Header className={'py-4'}/>
      {children}
      <Footer/>
      </body>
      </html>
  );
}
